import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";
import styles from "./layout.module.css";
import CacheProvider from "@context/cacheProvider";
import NavigationBar from "./navigationBar";
import Footer from "./footer";
import Head from "next/head";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css?family=Maitree"
          ref="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Cairo"
          ref="stylesheet"
        />
        <link rel="preconnect" href="https://cdn.jsdelivr.net" />
        <meta name="color-scheme" content="dark" />
      </Head>
      <body className={styles["body"]}>
        <CacheProvider>
          <NavigationBar />
          {children}
          <Footer />
        </CacheProvider>
      </body>
    </html>
  );
}
